name: web_lko
version: 0.5.1
environment:
  sdk: '>=1.24.2'

dependencies:
  angular: '^4.0.0'
  angular_forms: '^1.0.0'
  angular_router: '^1.0.2'
  angular_components: '^0.6.0'
  rxdart: '^0.14.0+1'
  route: '^0.4.6'
  uuid: '^0.5.3'
  xml2json: '^2.0.9'
  yaml: '^2.1.12'
  mime: '^0.9.3'
  http: '^0.11.3+14'
  web_socket_channel: '^1.0.5'
  logging: '0.11.3+1'

dev_dependencies:
  angular_test: '^1.0.0'
  browser: '^0.10.0+2'
  dart_to_js_script_rewriter: '^1.0.3'
  test: '^0.12.24+4'

transformers:
- angular:
      $exclude:
        - lib/server
      entry_points:
        - web/main.dart
        - test/client/**_test.dart
- test/pub_serve:
      $include: test/**_test{.*,}.dart
- $dart2js:
      commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
#    release: dartdevc
